name: 'Gofmter'
author: 'Jérôme Pogeant'
description: 'Check code formatting using gofmt'
inputs:
  gofmt-path:
    description: 'Path used by gofmt command'
    required: false
    default: './'
outputs:
  gofmt-output:
    description: 'The gofmt output if the command fail'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.gofmt-path }}
branding:
  icon: 'check-circle'
  color: 'green'
